//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace getsetcode.Model
{
    public partial class GetsetcodeEntities : ObjectContext
    {
        public const string ConnectionString = "name=GetsetcodeEntities";
        public const string ContainerName = "GetsetcodeEntities";
    
        #region Constructors
    
        public GetsetcodeEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		init();
        }
    
        public GetsetcodeEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		init();
        }
    
        public GetsetcodeEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		init();
        }
    
        #endregion
    
        #region n-tier total disconnection
    	private void init()
    	{
    		this.ContextOptions.LazyLoadingEnabled = false;
    		this.ContextOptions.ProxyCreationEnabled = false;
    		disableTracking();
    	}
    
    	private void disableTracking()
    	{
    		Agencies.MergeOption = MergeOption.NoTracking;
    		Clients.MergeOption = MergeOption.NoTracking;
    		ContactFormSubmissions.MergeOption = MergeOption.NoTracking;
    		Contracts.MergeOption = MergeOption.NoTracking;
    		Frequencies.MergeOption = MergeOption.NoTracking;
    		History.MergeOption = MergeOption.NoTracking;
    		Images.MergeOption = MergeOption.NoTracking;
    		People.MergeOption = MergeOption.NoTracking;
    		Projects.MergeOption = MergeOption.NoTracking;
    		ProjectImages.MergeOption = MergeOption.NoTracking;
    		ProjectResponsibilities.MergeOption = MergeOption.NoTracking;
    		ProjectSkills.MergeOption = MergeOption.NoTracking;
    		Rates.MergeOption = MergeOption.NoTracking;
    		Skills.MergeOption = MergeOption.NoTracking;
    		Testimonials.MergeOption = MergeOption.NoTracking;
    		CurriculaVitae.MergeOption = MergeOption.NoTracking;
    		SkillCategories.MergeOption = MergeOption.NoTracking;
    	}

        #endregion
    
            #region ObjectSet Properties
    
        public ObjectSet<Agency> Agencies
        {
            get { return _agencies  ?? (_agencies = CreateObjectSet<Agency>("Agencies")); }
        }
        private ObjectSet<Agency> _agencies;
    
        public ObjectSet<Client> Clients
        {
            get { return _clients  ?? (_clients = CreateObjectSet<Client>("Clients")); }
        }
        private ObjectSet<Client> _clients;
    
        public ObjectSet<ContactFormSubmission> ContactFormSubmissions
        {
            get { return _contactFormSubmissions  ?? (_contactFormSubmissions = CreateObjectSet<ContactFormSubmission>("ContactFormSubmissions")); }
        }
        private ObjectSet<ContactFormSubmission> _contactFormSubmissions;
    
        public ObjectSet<Contract> Contracts
        {
            get { return _contracts  ?? (_contracts = CreateObjectSet<Contract>("Contracts")); }
        }
        private ObjectSet<Contract> _contracts;
    
        public ObjectSet<Frequency> Frequencies
        {
            get { return _frequencies  ?? (_frequencies = CreateObjectSet<Frequency>("Frequencies")); }
        }
        private ObjectSet<Frequency> _frequencies;
    
        public ObjectSet<HistoryItem> History
        {
            get { return _history  ?? (_history = CreateObjectSet<HistoryItem>("History")); }
        }
        private ObjectSet<HistoryItem> _history;
    
        public ObjectSet<Image> Images
        {
            get { return _images  ?? (_images = CreateObjectSet<Image>("Images")); }
        }
        private ObjectSet<Image> _images;
    
        public ObjectSet<Person> People
        {
            get { return _people  ?? (_people = CreateObjectSet<Person>("People")); }
        }
        private ObjectSet<Person> _people;
    
        public ObjectSet<Project> Projects
        {
            get { return _projects  ?? (_projects = CreateObjectSet<Project>("Projects")); }
        }
        private ObjectSet<Project> _projects;
    
        public ObjectSet<ProjectImage> ProjectImages
        {
            get { return _projectImages  ?? (_projectImages = CreateObjectSet<ProjectImage>("ProjectImages")); }
        }
        private ObjectSet<ProjectImage> _projectImages;
    
        public ObjectSet<ProjectResponsibility> ProjectResponsibilities
        {
            get { return _projectResponsibilities  ?? (_projectResponsibilities = CreateObjectSet<ProjectResponsibility>("ProjectResponsibilities")); }
        }
        private ObjectSet<ProjectResponsibility> _projectResponsibilities;
    
        public ObjectSet<ProjectSkill> ProjectSkills
        {
            get { return _projectSkills  ?? (_projectSkills = CreateObjectSet<ProjectSkill>("ProjectSkills")); }
        }
        private ObjectSet<ProjectSkill> _projectSkills;
    
        public ObjectSet<Rate> Rates
        {
            get { return _rates  ?? (_rates = CreateObjectSet<Rate>("Rates")); }
        }
        private ObjectSet<Rate> _rates;
    
        public ObjectSet<Skill> Skills
        {
            get { return _skills  ?? (_skills = CreateObjectSet<Skill>("Skills")); }
        }
        private ObjectSet<Skill> _skills;
    
        public ObjectSet<Testimonial> Testimonials
        {
            get { return _testimonials  ?? (_testimonials = CreateObjectSet<Testimonial>("Testimonials")); }
        }
        private ObjectSet<Testimonial> _testimonials;
    
        public ObjectSet<CurriculumVitae> CurriculaVitae
        {
            get { return _curriculaVitae  ?? (_curriculaVitae = CreateObjectSet<CurriculumVitae>("CurriculaVitae")); }
        }
        private ObjectSet<CurriculumVitae> _curriculaVitae;
    
        public ObjectSet<SkillCategory> SkillCategories
        {
            get { return _skillCategories  ?? (_skillCategories = CreateObjectSet<SkillCategory>("SkillCategories")); }
        }
        private ObjectSet<SkillCategory> _skillCategories;

            #endregion
    }
}
