//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Data.Mapping.EntityViewGenerationAttribute(typeof(Edm_EntityMappingGeneratedViews.ViewsForBaseEntitySetsEF1E1D5D16432E262AAF9334CEDD68ABF2A1E16A80B34F43721B9881C6D213D1))]

namespace Edm_EntityMappingGeneratedViews
{
    
    
    /// <Summary>
    /// The type contains views for EntitySets and AssociationSets that were generated at design time.
    /// </Summary>
    public sealed class ViewsForBaseEntitySetsEF1E1D5D16432E262AAF9334CEDD68ABF2A1E16A80B34F43721B9881C6D213D1 : System.Data.Mapping.EntityViewContainer
    {
        
        /// <Summary>
        /// The constructor stores the views for the extents and also the hash values generated based on the metadata and mapping closure and views.
        /// </Summary>
        public ViewsForBaseEntitySetsEF1E1D5D16432E262AAF9334CEDD68ABF2A1E16A80B34F43721B9881C6D213D1()
        {
            this.EdmEntityContainerName = "GetsetcodeEntities";
            this.StoreEntityContainerName = "getsetcodeModelStoreContainer";
            this.HashOverMappingClosure = "2076d90c1b5cb28fdc57e150551354d5b7e5d574a7e619c48b0fd24bef9d92b6";
            this.HashOverAllExtentViews = "56528db26b37dbc7f0c357abe4fa66257c84af5e30ee32900b9c5a3cf7ab8a29";
            this.ViewCount = 40;
        }
        
        /// <Summary>
        /// The method returns the view for the index given.
        /// </Summary>
        protected override System.Collections.Generic.KeyValuePair<string, string> GetViewAt(int index)
        {
            if ((index == 0))
            {
                return GetView0();
            }
            if ((index == 1))
            {
                return GetView1();
            }
            if ((index == 2))
            {
                return GetView2();
            }
            if ((index == 3))
            {
                return GetView3();
            }
            if ((index == 4))
            {
                return GetView4();
            }
            if ((index == 5))
            {
                return GetView5();
            }
            if ((index == 6))
            {
                return GetView6();
            }
            if ((index == 7))
            {
                return GetView7();
            }
            if ((index == 8))
            {
                return GetView8();
            }
            if ((index == 9))
            {
                return GetView9();
            }
            if ((index == 10))
            {
                return GetView10();
            }
            if ((index == 11))
            {
                return GetView11();
            }
            if ((index == 12))
            {
                return GetView12();
            }
            if ((index == 13))
            {
                return GetView13();
            }
            if ((index == 14))
            {
                return GetView14();
            }
            if ((index == 15))
            {
                return GetView15();
            }
            if ((index == 16))
            {
                return GetView16();
            }
            if ((index == 17))
            {
                return GetView17();
            }
            if ((index == 18))
            {
                return GetView18();
            }
            if ((index == 19))
            {
                return GetView19();
            }
            if ((index == 20))
            {
                return GetView20();
            }
            if ((index == 21))
            {
                return GetView21();
            }
            if ((index == 22))
            {
                return GetView22();
            }
            if ((index == 23))
            {
                return GetView23();
            }
            if ((index == 24))
            {
                return GetView24();
            }
            if ((index == 25))
            {
                return GetView25();
            }
            if ((index == 26))
            {
                return GetView26();
            }
            if ((index == 27))
            {
                return GetView27();
            }
            if ((index == 28))
            {
                return GetView28();
            }
            if ((index == 29))
            {
                return GetView29();
            }
            if ((index == 30))
            {
                return GetView30();
            }
            if ((index == 31))
            {
                return GetView31();
            }
            if ((index == 32))
            {
                return GetView32();
            }
            if ((index == 33))
            {
                return GetView33();
            }
            if ((index == 34))
            {
                return GetView34();
            }
            if ((index == 35))
            {
                return GetView35();
            }
            if ((index == 36))
            {
                return GetView36();
            }
            if ((index == 37))
            {
                return GetView37();
            }
            if ((index == 38))
            {
                return GetView38();
            }
            if ((index == 39))
            {
                return GetView39();
            }
            throw new System.IndexOutOfRangeException();
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Agency
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView0()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Agency", @"
    SELECT VALUE -- Constructing Agency
        [getsetcode.Model.Store.Agency](T1.Agency_AgencyId, T1.Agency_Name, T1.Agency_Address, T1.Agency_Phone, T1.Agency_Email, T1.Agency_PrimaryContactId)
    FROM (
        SELECT 
            T.AgencyId AS Agency_AgencyId, 
            T.Name AS Agency_Name, 
            T.Address AS Agency_Address, 
            T.Phone AS Agency_Phone, 
            T.Email AS Agency_Email, 
            T.PrimaryContactId AS Agency_PrimaryContactId, 
            True AS _from0
        FROM GetsetcodeEntities.Agencies AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Client
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView1()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Client", @"
    SELECT VALUE -- Constructing Client
        [getsetcode.Model.Store.Client](T1.Client_ClientId, T1.Client_Name, T1.Client_ShortName, T1.Client_Address, T1.Client_BriefDescription, T1.Client_SummaryHtml, T1.Client_Website, T1.Client_LogoId, T1.Client_Featured)
    FROM (
        SELECT 
            T.ClientId AS Client_ClientId, 
            T.Name AS Client_Name, 
            T.ShortName AS Client_ShortName, 
            T.Address AS Client_Address, 
            T.BriefDescription AS Client_BriefDescription, 
            T.SummaryHtml AS Client_SummaryHtml, 
            T.Website AS Client_Website, 
            T.LogoId AS Client_LogoId, 
            T.Featured AS Client_Featured, 
            True AS _from0
        FROM GetsetcodeEntities.Clients AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Contract
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView2()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Contract", @"
    SELECT VALUE -- Constructing Contract
        [getsetcode.Model.Store.Contract](T1.Contract_ContractId, T1.Contract_ClientId, T1.Contract_StartDate, T1.Contract_EndDate, T1.Contract_AgencyId, T1.Contract_ContactDetails, T1.Contract_WorkDetails)
    FROM (
        SELECT 
            T.ContractId AS Contract_ContractId, 
            T.ClientId AS Contract_ClientId, 
            T.StartDate AS Contract_StartDate, 
            T.EndDate AS Contract_EndDate, 
            T.AgencyId AS Contract_AgencyId, 
            T.ContactDetails AS Contract_ContactDetails, 
            T.WorkDetails AS Contract_WorkDetails, 
            True AS _from0
        FROM GetsetcodeEntities.Contracts AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Frequency
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView3()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Frequency", @"
    SELECT VALUE -- Constructing Frequency
        [getsetcode.Model.Store.Frequency](T1.Frequency_FrequencyId, T1.Frequency_Text)
    FROM (
        SELECT 
            T.FrequencyId AS Frequency_FrequencyId, 
            T.Text AS Frequency_Text, 
            True AS _from0
        FROM GetsetcodeEntities.Frequencies AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.History
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView4()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.History", @"
    SELECT VALUE -- Constructing History
        [getsetcode.Model.Store.History](T1.History_HistoryId, T1.History_DateStamp, T1.History_ProjectId, T1.History_ClientId, T1.History_TestimonialId)
    FROM (
        SELECT 
            T.HistoryId AS History_HistoryId, 
            T.DateStamp AS History_DateStamp, 
            T.ProjectId AS History_ProjectId, 
            T.ClientId AS History_ClientId, 
            T.TestimonialId AS History_TestimonialId, 
            True AS _from0
        FROM GetsetcodeEntities.History AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Image
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView5()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Image", @"
    SELECT VALUE -- Constructing Image
        [getsetcode.Model.Store.Image](T1.Image_ImageId, T1.Image_Title, T1.Image_FileName, T1.Image_Width, T1.Image_Height, T1.Image_ThumbnailId)
    FROM (
        SELECT 
            T.ImageId AS Image_ImageId, 
            T.Title AS Image_Title, 
            T.FileName AS Image_FileName, 
            T.Width AS Image_Width, 
            T.Height AS Image_Height, 
            T.ThumbnailId AS Image_ThumbnailId, 
            True AS _from0
        FROM GetsetcodeEntities.Images AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Person
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView6()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Person", @"
    SELECT VALUE -- Constructing Person
        [getsetcode.Model.Store.Person](T1.Person_PersonId, T1.Person_Name, T1.Person_OfficePhone, T1.Person_MobilePhone, T1.Person_EmailAddress, T1.Person_Active, T1.Person_ThumbnailId)
    FROM (
        SELECT 
            T.PersonId AS Person_PersonId, 
            T.Name AS Person_Name, 
            T.OfficePhone AS Person_OfficePhone, 
            T.MobilePhone AS Person_MobilePhone, 
            T.EmailAddress AS Person_EmailAddress, 
            T.Active AS Person_Active, 
            T.ThumbnailId AS Person_ThumbnailId, 
            True AS _from0
        FROM GetsetcodeEntities.People AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Project
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView7()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Project", @"
    SELECT VALUE -- Constructing Project
        [getsetcode.Model.Store.Project](T1.Project_ProjectId, T1.Project_Name, T1.Project_ShortName, T1.Project_BriefSummary, T1.Project_SummaryHtml, T1.Project_ThumbnailImageId, T1.Project_Featured, T1.Project_ClientId, T1.Project_StartDate, T1.Project_EndDate)
    FROM (
        SELECT 
            T.ProjectId AS Project_ProjectId, 
            T.Name AS Project_Name, 
            T.ShortName AS Project_ShortName, 
            T.BriefSummary AS Project_BriefSummary, 
            T.SummaryHtml AS Project_SummaryHtml, 
            T.ThumbnailImageId AS Project_ThumbnailImageId, 
            T.Featured AS Project_Featured, 
            T.ClientId AS Project_ClientId, 
            T.StartDate AS Project_StartDate, 
            T.EndDate AS Project_EndDate, 
            True AS _from0
        FROM GetsetcodeEntities.Projects AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.ProjectImage
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView8()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.ProjectImage", @"
    SELECT VALUE -- Constructing ProjectImage
        [getsetcode.Model.Store.ProjectImage](T1.ProjectImage_ProjectId, T1.ProjectImage_ImageId, T1.ProjectImage_Rank)
    FROM (
        SELECT 
            T.ProjectId AS ProjectImage_ProjectId, 
            T.ImageId AS ProjectImage_ImageId, 
            T.Rank AS ProjectImage_Rank, 
            True AS _from0
        FROM GetsetcodeEntities.ProjectImages AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.ProjectResponsibility
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView9()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.ProjectResponsibility", @"
    SELECT VALUE -- Constructing ProjectResponsibility
        [getsetcode.Model.Store.ProjectResponsibility](T1.ProjectResponsibility_ResponsibilityId, T1.ProjectResponsibility_ProjectId, T1.ProjectResponsibility_Description, T1.ProjectResponsibility_Rank)
    FROM (
        SELECT 
            T.ResponsibilityId AS ProjectResponsibility_ResponsibilityId, 
            T.ProjectId AS ProjectResponsibility_ProjectId, 
            T.Description AS ProjectResponsibility_Description, 
            T.Rank AS ProjectResponsibility_Rank, 
            True AS _from0
        FROM GetsetcodeEntities.ProjectResponsibilities AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.ProjectSkill
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView10()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.ProjectSkill", @"
    SELECT VALUE -- Constructing ProjectSkill
        [getsetcode.Model.Store.ProjectSkill](T1.ProjectSkill_ProjectId, T1.ProjectSkill_SkillId, T1.ProjectSkill_Rank, T1.ProjectSkill_Featured)
    FROM (
        SELECT 
            T.ProjectId AS ProjectSkill_ProjectId, 
            T.SkillId AS ProjectSkill_SkillId, 
            T.Rank AS ProjectSkill_Rank, 
            T.Featured AS ProjectSkill_Featured, 
            True AS _from0
        FROM GetsetcodeEntities.ProjectSkills AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Rate
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView11()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Rate", @"
    SELECT VALUE -- Constructing Rate
        [getsetcode.Model.Store.Rate](T1.Rate_RateId, T1.Rate_ContractId, T1.Rate_Amount, T1.Rate_FrequencyId, T1.Rate_StartDate, T1.Rate_EndDate)
    FROM (
        SELECT 
            T.RateId AS Rate_RateId, 
            T.ContractId AS Rate_ContractId, 
            T.Amount AS Rate_Amount, 
            T.FrequencyId AS Rate_FrequencyId, 
            T.StartDate AS Rate_StartDate, 
            T.EndDate AS Rate_EndDate, 
            True AS _from0
        FROM GetsetcodeEntities.Rates AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Skill
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView12()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Skill", @"
    SELECT VALUE -- Constructing Skill
        [getsetcode.Model.Store.Skill](T1.Skill_SkillId, T1.Skill_SkillCategoryId, T1.Skill_Name, T1.Skill_ShortName, T1.Skill_Summary, T1.Skill_DateAcquired, T1.Skill_CurrentVersion, T1.Skill_IsCoreSkill, T1.Skill_Rank)
    FROM (
        SELECT 
            T.SkillId AS Skill_SkillId, 
            T.SkillCategoryId AS Skill_SkillCategoryId, 
            T.Name AS Skill_Name, 
            T.ShortName AS Skill_ShortName, 
            T.Summary AS Skill_Summary, 
            T.DateAcquired AS Skill_DateAcquired, 
            T.CurrentVersion AS Skill_CurrentVersion, 
            T.IsCoreSkill AS Skill_IsCoreSkill, 
            T.Rank AS Skill_Rank, 
            True AS _from0
        FROM GetsetcodeEntities.Skills AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.Testimonial
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView13()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.Testimonial", @"
    SELECT VALUE -- Constructing Testimonial
        [getsetcode.Model.Store.Testimonial](T1.Testimonial_TestimonialId, T1.Testimonial_PersonId, T1.Testimonial_ClientId, T1.Testimonial_Role, T1.Testimonial_Quote, T1.Testimonial_Date)
    FROM (
        SELECT 
            T.TestimonialId AS Testimonial_TestimonialId, 
            T.PersonId AS Testimonial_PersonId, 
            T.ClientId AS Testimonial_ClientId, 
            T.Role AS Testimonial_Role, 
            T.Quote AS Testimonial_Quote, 
            T.Date AS Testimonial_Date, 
            True AS _from0
        FROM GetsetcodeEntities.Testimonials AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.SkillCategory
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView14()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.SkillCategory", @"
    SELECT VALUE -- Constructing SkillCategory
        [getsetcode.Model.Store.SkillCategory](T1.SkillCategory_SkillCategoryId, T1.SkillCategory_SkillCategory, T1.SkillCategory_Rank)
    FROM (
        SELECT 
            T.SkillCategoryId AS SkillCategory_SkillCategoryId, 
            T.SkillCategoryText AS SkillCategory_SkillCategory, 
            T.Rank AS SkillCategory_Rank, 
            True AS _from0
        FROM GetsetcodeEntities.SkillCategories AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.AgencyPerson
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView15()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.AgencyPerson", @"
    SELECT VALUE -- Constructing AgencyPerson
        [getsetcode.Model.Store.AgencyPerson](T1.AgencyPerson_AgencyId, T1.AgencyPerson_PersonId)
    FROM (
        SELECT 
            Key(T.Agency).AgencyId AS AgencyPerson_AgencyId, 
            Key(T.Person).PersonId AS AgencyPerson_PersonId, 
            True AS _from0
        FROM GetsetcodeEntities.AgencyPerson AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.ClientPerson
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView16()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.ClientPerson", @"
    SELECT VALUE -- Constructing ClientPerson
        [getsetcode.Model.Store.ClientPerson](T1.ClientPerson_ClientId, T1.ClientPerson_PersonId)
    FROM (
        SELECT 
            Key(T.Client).ClientId AS ClientPerson_ClientId, 
            Key(T.Person).PersonId AS ClientPerson_PersonId, 
            True AS _from0
        FROM GetsetcodeEntities.ClientPerson AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.ProjectContract
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView17()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.ProjectContract", @"
    SELECT VALUE -- Constructing ProjectContract
        [getsetcode.Model.Store.ProjectContract](T1.ProjectContract_ContractId, T1.ProjectContract_ProjectId)
    FROM (
        SELECT 
            Key(T.Contract).ContractId AS ProjectContract_ContractId, 
            Key(T.Project).ProjectId AS ProjectContract_ProjectId, 
            True AS _from0
        FROM GetsetcodeEntities.ProjectContract AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Agencies
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView18()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Agencies", @"
    SELECT VALUE -- Constructing Agencies
        [getsetcode.Model.Agency](T1.Agency_AgencyId, T1.Agency_Name, T1.Agency_Address, T1.Agency_Phone, T1.Agency_Email, T1.Agency_PrimaryContactId)
    FROM (
        SELECT 
            T.AgencyId AS Agency_AgencyId, 
            T.Name AS Agency_Name, 
            T.Address AS Agency_Address, 
            T.Phone AS Agency_Phone, 
            T.Email AS Agency_Email, 
            T.PrimaryContactId AS Agency_PrimaryContactId, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Agency AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Clients
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView19()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Clients", @"
    SELECT VALUE -- Constructing Clients
        [getsetcode.Model.Client](T1.Client_ClientId, T1.Client_Name, T1.Client_ShortName, T1.Client_Address, T1.Client_BriefDescription, T1.Client_Website, T1.Client_Featured, T1.Client_LogoId, T1.Client_SummaryHtml)
    FROM (
        SELECT 
            T.ClientId AS Client_ClientId, 
            T.Name AS Client_Name, 
            T.ShortName AS Client_ShortName, 
            T.Address AS Client_Address, 
            T.BriefDescription AS Client_BriefDescription, 
            T.Website AS Client_Website, 
            T.Featured AS Client_Featured, 
            T.LogoId AS Client_LogoId, 
            T.SummaryHtml AS Client_SummaryHtml, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Client AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Contracts
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView20()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Contracts", @"
    SELECT VALUE -- Constructing Contracts
        [getsetcode.Model.Contract](T1.Contract_ContractId, T1.Contract_ClientId, T1.Contract_StartDate, T1.Contract_EndDate, T1.Contract_AgencyId, T1.Contract_ContactDetails, T1.Contract_WorkDetails)
    FROM (
        SELECT 
            T.ContractId AS Contract_ContractId, 
            T.ClientId AS Contract_ClientId, 
            T.StartDate AS Contract_StartDate, 
            T.EndDate AS Contract_EndDate, 
            T.AgencyId AS Contract_AgencyId, 
            T.ContactDetails AS Contract_ContactDetails, 
            T.WorkDetails AS Contract_WorkDetails, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Contract AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Frequencies
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView21()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Frequencies", @"
    SELECT VALUE -- Constructing Frequencies
        [getsetcode.Model.Frequency](T1.Frequency_FrequencyId, T1.Frequency_Text)
    FROM (
        SELECT 
            T.FrequencyId AS Frequency_FrequencyId, 
            T.Text AS Frequency_Text, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Frequency AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.History
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView22()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.History", @"
    SELECT VALUE -- Constructing History
        [getsetcode.Model.HistoryItem](T1.HistoryItem_HistoryId, T1.HistoryItem_DateStamp, T1.HistoryItem_ProjectId, T1.HistoryItem_ClientId, T1.HistoryItem_TestimonialId)
    FROM (
        SELECT 
            T.HistoryId AS HistoryItem_HistoryId, 
            T.DateStamp AS HistoryItem_DateStamp, 
            T.ProjectId AS HistoryItem_ProjectId, 
            T.ClientId AS HistoryItem_ClientId, 
            T.TestimonialId AS HistoryItem_TestimonialId, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.History AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Images
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView23()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Images", @"
    SELECT VALUE -- Constructing Images
        [getsetcode.Model.Image](T1.Image_ImageId, T1.Image_Title, T1.Image_FileName, T1.Image_Width, T1.Image_Height, T1.Image_ThumbnailId)
    FROM (
        SELECT 
            T.ImageId AS Image_ImageId, 
            T.Title AS Image_Title, 
            T.FileName AS Image_FileName, 
            T.Width AS Image_Width, 
            T.Height AS Image_Height, 
            T.ThumbnailId AS Image_ThumbnailId, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Image AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.People
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView24()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.People", @"
    SELECT VALUE -- Constructing People
        [getsetcode.Model.Person](T1.Person_PersonId, T1.Person_Name, T1.Person_OfficePhone, T1.Person_MobilePhone, T1.Person_EmailAddress, T1.Person_Active, T1.Person_ThumbnailId)
    FROM (
        SELECT 
            T.PersonId AS Person_PersonId, 
            T.Name AS Person_Name, 
            T.OfficePhone AS Person_OfficePhone, 
            T.MobilePhone AS Person_MobilePhone, 
            T.EmailAddress AS Person_EmailAddress, 
            T.Active AS Person_Active, 
            T.ThumbnailId AS Person_ThumbnailId, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Person AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Projects
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView25()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Projects", @"
    SELECT VALUE -- Constructing Projects
        [getsetcode.Model.Project](T1.Project_ProjectId, T1.Project_Name, T1.Project_ShortName, T1.Project_BriefSummary, T1.Project_Featured, T1.Project_ClientId, T1.Project_ThumbnailImageId, T1.Project_SummaryHtml, T1.Project_StartDate, T1.Project_EndDate)
    FROM (
        SELECT 
            T.ProjectId AS Project_ProjectId, 
            T.Name AS Project_Name, 
            T.ShortName AS Project_ShortName, 
            T.BriefSummary AS Project_BriefSummary, 
            T.Featured AS Project_Featured, 
            T.ClientId AS Project_ClientId, 
            T.ThumbnailImageId AS Project_ThumbnailImageId, 
            T.SummaryHtml AS Project_SummaryHtml, 
            T.StartDate AS Project_StartDate, 
            T.EndDate AS Project_EndDate, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Project AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.ProjectImages
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView26()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.ProjectImages", @"
    SELECT VALUE -- Constructing ProjectImages
        [getsetcode.Model.ProjectImage](T1.ProjectImage_ProjectId, T1.ProjectImage_ImageId, T1.ProjectImage_Rank)
    FROM (
        SELECT 
            T.ProjectId AS ProjectImage_ProjectId, 
            T.ImageId AS ProjectImage_ImageId, 
            T.Rank AS ProjectImage_Rank, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.ProjectImage AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.ProjectResponsibilities
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView27()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.ProjectResponsibilities", @"
    SELECT VALUE -- Constructing ProjectResponsibilities
        [getsetcode.Model.ProjectResponsibility](T1.ProjectResponsibility_ResponsibilityId, T1.ProjectResponsibility_ProjectId, T1.ProjectResponsibility_Description, T1.ProjectResponsibility_Rank)
    FROM (
        SELECT 
            T.ResponsibilityId AS ProjectResponsibility_ResponsibilityId, 
            T.ProjectId AS ProjectResponsibility_ProjectId, 
            T.Description AS ProjectResponsibility_Description, 
            T.Rank AS ProjectResponsibility_Rank, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.ProjectResponsibility AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.ProjectSkills
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView28()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.ProjectSkills", @"
    SELECT VALUE -- Constructing ProjectSkills
        [getsetcode.Model.ProjectSkill](T1.ProjectSkill_ProjectId, T1.ProjectSkill_SkillId, T1.ProjectSkill_Rank, T1.ProjectSkill_Featured)
    FROM (
        SELECT 
            T.ProjectId AS ProjectSkill_ProjectId, 
            T.SkillId AS ProjectSkill_SkillId, 
            T.Rank AS ProjectSkill_Rank, 
            T.Featured AS ProjectSkill_Featured, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.ProjectSkill AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Rates
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView29()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Rates", @"
    SELECT VALUE -- Constructing Rates
        [getsetcode.Model.Rate](T1.Rate_RateId, T1.Rate_ContractId, T1.Rate_Amount, T1.Rate_FrequencyId, T1.Rate_StartDate, T1.Rate_EndDate)
    FROM (
        SELECT 
            T.RateId AS Rate_RateId, 
            T.ContractId AS Rate_ContractId, 
            T.Amount AS Rate_Amount, 
            T.FrequencyId AS Rate_FrequencyId, 
            T.StartDate AS Rate_StartDate, 
            T.EndDate AS Rate_EndDate, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Rate AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Skills
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView30()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Skills", @"
    SELECT VALUE -- Constructing Skills
        [getsetcode.Model.Skill](T1.Skill_SkillId, T1.Skill_Name, T1.Skill_ShortName, T1.Skill_Summary, T1.Skill_DateAcquired, T1.Skill_CurrentVersion, T1.Skill_IsCoreSkill, T1.Skill_Rank, T1.Skill_SkillCategoryId)
    FROM (
        SELECT 
            T.SkillId AS Skill_SkillId, 
            T.Name AS Skill_Name, 
            T.ShortName AS Skill_ShortName, 
            T.Summary AS Skill_Summary, 
            T.DateAcquired AS Skill_DateAcquired, 
            T.CurrentVersion AS Skill_CurrentVersion, 
            T.IsCoreSkill AS Skill_IsCoreSkill, 
            T.Rank AS Skill_Rank, 
            T.SkillCategoryId AS Skill_SkillCategoryId, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Skill AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.Testimonials
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView31()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.Testimonials", @"
    SELECT VALUE -- Constructing Testimonials
        [getsetcode.Model.Testimonial](T1.Testimonial_TestimonialId, T1.Testimonial_PersonId, T1.Testimonial_Date, T1.Testimonial_ClientId, T1.Testimonial_Quote, T1.Testimonial_Role)
    FROM (
        SELECT 
            T.TestimonialId AS Testimonial_TestimonialId, 
            T.PersonId AS Testimonial_PersonId, 
            T.Date AS Testimonial_Date, 
            T.ClientId AS Testimonial_ClientId, 
            T.Quote AS Testimonial_Quote, 
            T.Role AS Testimonial_Role, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.Testimonial AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.SkillCategories
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView32()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.SkillCategories", @"
    SELECT VALUE -- Constructing SkillCategories
        [getsetcode.Model.SkillCategory](T1.SkillCategory_SkillCategoryId, T1.SkillCategory_SkillCategoryText, T1.SkillCategory_Rank)
    FROM (
        SELECT 
            T.SkillCategoryId AS SkillCategory_SkillCategoryId, 
            T.SkillCategory AS SkillCategory_SkillCategoryText, 
            T.Rank AS SkillCategory_Rank, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.SkillCategory AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.AgencyPerson
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView33()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.AgencyPerson", @"
    SELECT VALUE -- Constructing AgencyPerson
        [getsetcode.Model.AgencyPerson](T3.AgencyPerson_Agency, T3.AgencyPerson_Person)
    FROM (
        SELECT -- Constructing Agency
            CreateRef(GetsetcodeEntities.Agencies, row(T2.AgencyPerson_Agency_AgencyId),[getsetcode.Model.Agency]) AS AgencyPerson_Agency, 
            T2.AgencyPerson_Person
        FROM (
            SELECT -- Constructing Person
                CreateRef(GetsetcodeEntities.People, row(T1.AgencyPerson_Person_PersonId),[getsetcode.Model.Person]) AS AgencyPerson_Person, 
                T1.AgencyPerson_Agency_AgencyId
            FROM (
                SELECT 
                    T.AgencyId AS AgencyPerson_Agency_AgencyId, 
                    T.PersonId AS AgencyPerson_Person_PersonId, 
                    True AS _from0
                FROM getsetcodeModelStoreContainer.AgencyPerson AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.ClientPerson
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView34()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.ClientPerson", @"
    SELECT VALUE -- Constructing ClientPerson
        [getsetcode.Model.ClientPerson](T3.ClientPerson_Client, T3.ClientPerson_Person)
    FROM (
        SELECT -- Constructing Client
            CreateRef(GetsetcodeEntities.Clients, row(T2.ClientPerson_Client_ClientId),[getsetcode.Model.Client]) AS ClientPerson_Client, 
            T2.ClientPerson_Person
        FROM (
            SELECT -- Constructing Person
                CreateRef(GetsetcodeEntities.People, row(T1.ClientPerson_Person_PersonId),[getsetcode.Model.Person]) AS ClientPerson_Person, 
                T1.ClientPerson_Client_ClientId
            FROM (
                SELECT 
                    T.ClientId AS ClientPerson_Client_ClientId, 
                    T.PersonId AS ClientPerson_Person_PersonId, 
                    True AS _from0
                FROM getsetcodeModelStoreContainer.ClientPerson AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.ProjectContract
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView35()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.ProjectContract", @"
    SELECT VALUE -- Constructing ProjectContract
        [getsetcode.Model.ProjectContract](T3.ProjectContract_Contract, T3.ProjectContract_Project)
    FROM (
        SELECT -- Constructing Contract
            CreateRef(GetsetcodeEntities.Contracts, row(T2.ProjectContract_Contract_ContractId),[getsetcode.Model.Contract]) AS ProjectContract_Contract, 
            T2.ProjectContract_Project
        FROM (
            SELECT -- Constructing Project
                CreateRef(GetsetcodeEntities.Projects, row(T1.ProjectContract_Project_ProjectId),[getsetcode.Model.Project]) AS ProjectContract_Project, 
                T1.ProjectContract_Contract_ContractId
            FROM (
                SELECT 
                    T.ContractId AS ProjectContract_Contract_ContractId, 
                    T.ProjectId AS ProjectContract_Project_ProjectId, 
                    True AS _from0
                FROM getsetcodeModelStoreContainer.ProjectContract AS T
            ) AS T1
        ) AS T2
    ) AS T3");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.ContactFormSubmission
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView36()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.ContactFormSubmission", @"
    SELECT VALUE -- Constructing ContactFormSubmission
        [getsetcode.Model.Store.ContactFormSubmission](T1.ContactFormSubmission_SubmissionId, T1.ContactFormSubmission_Name, T1.ContactFormSubmission_EmailAddress, T1.ContactFormSubmission_Message, T1.ContactFormSubmission_MailingList, T1.ContactFormSubmission_DateStamp, T1.ContactFormSubmission_EmailSent)
    FROM (
        SELECT 
            T.SubmissionId AS ContactFormSubmission_SubmissionId, 
            T.Name AS ContactFormSubmission_Name, 
            T.EmailAddress AS ContactFormSubmission_EmailAddress, 
            T.Message AS ContactFormSubmission_Message, 
            T.MailingList AS ContactFormSubmission_MailingList, 
            T.DateStamp AS ContactFormSubmission_DateStamp, 
            T.EmailSent AS ContactFormSubmission_EmailSent, 
            True AS _from0
        FROM GetsetcodeEntities.ContactFormSubmissions AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.ContactFormSubmissions
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView37()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.ContactFormSubmissions", @"
    SELECT VALUE -- Constructing ContactFormSubmissions
        [getsetcode.Model.ContactFormSubmission](T1.ContactFormSubmission_SubmissionId, T1.ContactFormSubmission_Name, T1.ContactFormSubmission_EmailAddress, T1.ContactFormSubmission_Message, T1.ContactFormSubmission_MailingList, T1.ContactFormSubmission_DateStamp, T1.ContactFormSubmission_EmailSent)
    FROM (
        SELECT 
            T.SubmissionId AS ContactFormSubmission_SubmissionId, 
            T.Name AS ContactFormSubmission_Name, 
            T.EmailAddress AS ContactFormSubmission_EmailAddress, 
            T.Message AS ContactFormSubmission_Message, 
            T.MailingList AS ContactFormSubmission_MailingList, 
            T.DateStamp AS ContactFormSubmission_DateStamp, 
            T.EmailSent AS ContactFormSubmission_EmailSent, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.ContactFormSubmission AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for getsetcodeModelStoreContainer.CurriculumVitae
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView38()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("getsetcodeModelStoreContainer.CurriculumVitae", @"
    SELECT VALUE -- Constructing CurriculumVitae
        [getsetcode.Model.Store.CurriculumVitae](T1.CurriculumVitae_Version, T1.CurriculumVitae_FileName, T1.CurriculumVitae_WordVersion, T1.CurriculumVitae_PdfVersion, T1.CurriculumVitae_DateAdded)
    FROM (
        SELECT 
            T.Version AS CurriculumVitae_Version, 
            T.FileName AS CurriculumVitae_FileName, 
            T.WordVersion AS CurriculumVitae_WordVersion, 
            T.PdfVersion AS CurriculumVitae_PdfVersion, 
            T.DateAdded AS CurriculumVitae_DateAdded, 
            True AS _from0
        FROM GetsetcodeEntities.CurriculaVitae AS T
    ) AS T1");
        }
        
        /// <Summary>
        /// return view for GetsetcodeEntities.CurriculaVitae
        /// </Summary>
        private System.Collections.Generic.KeyValuePair<string, string> GetView39()
        {
            return new System.Collections.Generic.KeyValuePair<string, string>("GetsetcodeEntities.CurriculaVitae", @"
    SELECT VALUE -- Constructing CurriculaVitae
        [getsetcode.Model.CurriculumVitae](T1.CurriculumVitae_Version, T1.CurriculumVitae_FileName, T1.CurriculumVitae_WordVersion, T1.CurriculumVitae_PdfVersion, T1.CurriculumVitae_DateAdded)
    FROM (
        SELECT 
            T.Version AS CurriculumVitae_Version, 
            T.FileName AS CurriculumVitae_FileName, 
            T.WordVersion AS CurriculumVitae_WordVersion, 
            T.PdfVersion AS CurriculumVitae_PdfVersion, 
            T.DateAdded AS CurriculumVitae_DateAdded, 
            True AS _from0
        FROM getsetcodeModelStoreContainer.CurriculumVitae AS T
    ) AS T1");
        }
    }
}
