//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace getsetcode.Model
{
    public partial class ContactFormSubmission
    {
        #region Primitive Properties
    
        public virtual int SubmissionId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string EmailAddress
        {
            get;
            set;
        }
    
        public virtual string Message
        {
            get;
            set;
        }
    
        public virtual bool MailingList
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateStamp
        {
            get;
            set;
        }
    
        public virtual bool EmailSent
        {
            get;
            set;
        }

        #endregion
    }
}
