//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace getsetcode.Model
{
    public partial class CurriculumVitae
    {
        #region Primitive Properties
    
        public virtual double Version
        {
            get;
            set;
        }
    
        public virtual string FileName
        {
            get;
            set;
        }
    
        public virtual bool WordVersion
        {
            get;
            set;
        }
    
        public virtual bool PdfVersion
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateAdded
        {
            get;
            set;
        }

        #endregion
    }
}
