//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace getsetcode.Model
{
    public partial class Frequency
    {
        #region Primitive Properties
    
        public virtual byte FrequencyId
        {
            get;
            set;
        }
    
        public virtual string Text
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Rate> Rates
        {
            get
            {
                if (_rates == null)
                {
                    var newCollection = new FixupCollection<Rate>();
                    newCollection.CollectionChanged += FixupRates;
                    _rates = newCollection;
                }
                return _rates;
            }
            set
            {
                if (!ReferenceEquals(_rates, value))
                {
                    var previousValue = _rates as FixupCollection<Rate>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupRates;
                    }
                    _rates = value;
                    var newValue = value as FixupCollection<Rate>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupRates;
                    }
                }
            }
        }
        private ICollection<Rate> _rates;

        #endregion
        #region Association Fixup
    
        private void FixupRates(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Rate item in e.NewItems)
                {
                    item.Frequency = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Rate item in e.OldItems)
                {
                    if (ReferenceEquals(item.Frequency, this))
                    {
                        item.Frequency = null;
                    }
                }
            }
        }

        #endregion
    }
}
