//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace getsetcode.Model
{
    public partial class ProjectSkill
    {
        #region Primitive Properties
    
        public virtual int ProjectId
        {
            get { return _projectId; }
            set
            {
                if (_projectId != value)
                {
                    if (Project != null && Project.ProjectId != value)
                    {
                        Project = null;
                    }
                    _projectId = value;
                }
            }
        }
        private int _projectId;
    
        public virtual int SkillId
        {
            get { return _skillId; }
            set
            {
                if (_skillId != value)
                {
                    if (Skill != null && Skill.SkillId != value)
                    {
                        Skill = null;
                    }
                    _skillId = value;
                }
            }
        }
        private int _skillId;
    
        public virtual byte Rank
        {
            get;
            set;
        }
    
        public virtual bool Featured
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Project Project
        {
            get { return _project; }
            set
            {
                if (!ReferenceEquals(_project, value))
                {
                    var previousValue = _project;
                    _project = value;
                    FixupProject(previousValue);
                }
            }
        }
        private Project _project;
    
        public virtual Skill Skill
        {
            get { return _skill; }
            set
            {
                if (!ReferenceEquals(_skill, value))
                {
                    var previousValue = _skill;
                    _skill = value;
                    FixupSkill(previousValue);
                }
            }
        }
        private Skill _skill;

        #endregion
        #region Association Fixup
    
        private void FixupProject(Project previousValue)
        {
            if (previousValue != null && previousValue.ProjectSkills.Contains(this))
            {
                previousValue.ProjectSkills.Remove(this);
            }
    
            if (Project != null)
            {
                if (!Project.ProjectSkills.Contains(this))
                {
                    Project.ProjectSkills.Add(this);
                }
                if (ProjectId != Project.ProjectId)
                {
                    ProjectId = Project.ProjectId;
                }
            }
        }
    
        private void FixupSkill(Skill previousValue)
        {
            if (previousValue != null && previousValue.ProjectSkills.Contains(this))
            {
                previousValue.ProjectSkills.Remove(this);
            }
    
            if (Skill != null)
            {
                if (!Skill.ProjectSkills.Contains(this))
                {
                    Skill.ProjectSkills.Add(this);
                }
                if (SkillId != Skill.SkillId)
                {
                    SkillId = Skill.SkillId;
                }
            }
        }

        #endregion
    }
}
