//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace getsetcode.Model
{
    public partial class Rate
    {
        #region Primitive Properties
    
        public virtual int RateId
        {
            get;
            set;
        }
    
        public virtual int ContractId
        {
            get { return _contractId; }
            set
            {
                if (_contractId != value)
                {
                    if (Contract != null && Contract.ContractId != value)
                    {
                        Contract = null;
                    }
                    _contractId = value;
                }
            }
        }
        private int _contractId;
    
        public virtual decimal Amount
        {
            get;
            set;
        }
    
        public virtual byte FrequencyId
        {
            get { return _frequencyId; }
            set
            {
                if (_frequencyId != value)
                {
                    if (Frequency != null && Frequency.FrequencyId != value)
                    {
                        Frequency = null;
                    }
                    _frequencyId = value;
                }
            }
        }
        private byte _frequencyId;
    
        public virtual System.DateTime StartDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime EndDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Contract Contract
        {
            get { return _contract; }
            set
            {
                if (!ReferenceEquals(_contract, value))
                {
                    var previousValue = _contract;
                    _contract = value;
                    FixupContract(previousValue);
                }
            }
        }
        private Contract _contract;
    
        public virtual Frequency Frequency
        {
            get { return _frequency; }
            set
            {
                if (!ReferenceEquals(_frequency, value))
                {
                    var previousValue = _frequency;
                    _frequency = value;
                    FixupFrequency(previousValue);
                }
            }
        }
        private Frequency _frequency;

        #endregion
        #region Association Fixup
    
        private void FixupContract(Contract previousValue)
        {
            if (previousValue != null && previousValue.Rates.Contains(this))
            {
                previousValue.Rates.Remove(this);
            }
    
            if (Contract != null)
            {
                if (!Contract.Rates.Contains(this))
                {
                    Contract.Rates.Add(this);
                }
                if (ContractId != Contract.ContractId)
                {
                    ContractId = Contract.ContractId;
                }
            }
        }
    
        private void FixupFrequency(Frequency previousValue)
        {
            if (previousValue != null && previousValue.Rates.Contains(this))
            {
                previousValue.Rates.Remove(this);
            }
    
            if (Frequency != null)
            {
                if (!Frequency.Rates.Contains(this))
                {
                    Frequency.Rates.Add(this);
                }
                if (FrequencyId != Frequency.FrequencyId)
                {
                    FrequencyId = Frequency.FrequencyId;
                }
            }
        }

        #endregion
    }
}
