//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace getsetcode.Model
{
    public partial class SkillCategory
    {
        #region Primitive Properties
    
        public virtual byte SkillCategoryId
        {
            get;
            set;
        }
    
        public virtual string SkillCategoryText
        {
            get;
            set;
        }
    
        public virtual byte Rank
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Skill> Skills
        {
            get
            {
                if (_skills == null)
                {
                    var newCollection = new FixupCollection<Skill>();
                    newCollection.CollectionChanged += FixupSkills;
                    _skills = newCollection;
                }
                return _skills;
            }
            set
            {
                if (!ReferenceEquals(_skills, value))
                {
                    var previousValue = _skills as FixupCollection<Skill>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSkills;
                    }
                    _skills = value;
                    var newValue = value as FixupCollection<Skill>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSkills;
                    }
                }
            }
        }
        private ICollection<Skill> _skills;

        #endregion
        #region Association Fixup
    
        private void FixupSkills(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Skill item in e.NewItems)
                {
                    item.SkillCategory = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Skill item in e.OldItems)
                {
                    if (ReferenceEquals(item.SkillCategory, this))
                    {
                        item.SkillCategory = null;
                    }
                }
            }
        }

        #endregion
    }
}
